// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkgnfQ90-3hV21QqrPF6-lCwljncwd9bY',
    appId: '1:812965533254:web:b1a4fdfca57dedda69dc47',
    messagingSenderId: '812965533254',
    projectId: 'deardiary-49853',
    authDomain: 'deardiary-49853.firebaseapp.com',
    storageBucket: 'deardiary-49853.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCHELui_e8YKRvactrOX2Xb4FBKPakCFM',
    appId: '1:812965533254:android:7770ccd9ea10672369dc47',
    messagingSenderId: '812965533254',
    projectId: 'deardiary-49853',
    storageBucket: 'deardiary-49853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyjNQOP0RaPeF0TdmhNxWntbUJXPyL5ek',
    appId: '1:812965533254:ios:ef3936b10fbdf78e69dc47',
    messagingSenderId: '812965533254',
    projectId: 'deardiary-49853',
    storageBucket: 'deardiary-49853.appspot.com',
    androidClientId: '812965533254-5k18e9amcue65gs5d3eph8q59vggfdc4.apps.googleusercontent.com',
    iosClientId: '812965533254-k0uq6m822239som5sq7mur499klfr70a.apps.googleusercontent.com',
    iosBundleId: 'com.example.dearDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyjNQOP0RaPeF0TdmhNxWntbUJXPyL5ek',
    appId: '1:812965533254:ios:80a5a3a8c083731c69dc47',
    messagingSenderId: '812965533254',
    projectId: 'deardiary-49853',
    storageBucket: 'deardiary-49853.appspot.com',
    androidClientId: '812965533254-5k18e9amcue65gs5d3eph8q59vggfdc4.apps.googleusercontent.com',
    iosClientId: '812965533254-o73bi658h8fndb8k39ur3ugbqs9lajn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.dearDiary.RunnerTests',
  );
}
